"""
Django settings for testimonios project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from decouple import config, Csv
from datetime import timedelta
import os 
import cloudinary
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app.apps.AppConfig',
    'rest_framework',
    'rest_framework_simplejwt', 
    'drf_spectacular', #django spectacular sirve como documentacion de swagger
    'corsheaders',
    'pwa',
    'cloudinary', 
    'cloudinary_storage',  
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de cualquier middleware que maneje solicitudes
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'testimonios.middleware.DisableAdminLogMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Testimonial",


    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Testimonial",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "images/logo1.png",
    
    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "images/logo1.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",


    # Welcome text on the login screen
    "welcome_sign": "Bienvenido. Por favor ingrese sus datos",

    # Copyright on the footer
    "copyright": "Testimonial",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
  

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    
    #############
    # User Menu #########@eqweqw@@@@@@@@
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Docs", "url": "https://apitestimonial.vercel.app", "new_window": False},
   
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages", 
            "url": "make_messages", 
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    
    "custom_css": "css/custom_login.css",
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
}


ROOT_URLCONF = 'testimonios.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Asegúrate de que esta línea esté presente
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testimonios.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Configuración de Cloudinary (agrega al final del archivo)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

cloudinary.config(
    cloud_name=CLOUDINARY_STORAGE['CLOUD_NAME'],
    api_key=CLOUDINARY_STORAGE['API_KEY'],
    api_secret=CLOUDINARY_STORAGE['API_SECRET']
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

AUTH_USER_MODEL = 'app.User'
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Define la ruta para STATIC_ROOT
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Aqui indico que todo el mundo pueda consumir la api porque se pidio que sea libre
CORS_ALLOW_ALL_ORIGINS = True


CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
REST_FRAMEWORK = {

    #DRF JWT
       'DEFAULT_AUTHENTICATION_CLASSES': (
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ),
    #Funcionalidad de limites de peticiones por la misma IP
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',  # Limit unauthenticated users to 60 requests per hour
        'user': '600/hour',  # Limit authenticated users to 600 requests per hour
    },

    #PERMISOS
       'DEFAULT_PERMISSION_CLASS': ('rest_framework.permissions.IsAuthenticated',),
    #DRF SPECTACULAR
       'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
  
   }


SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    #Tiempo de expiracion del TOKEN

    #PARA DESARROLLO ESTA CONFIGURACION

    # Tiempo de vida del token de acceso (default: 5 minutos)
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hora
    ## Tiempo de vida del token de refresco (default: 1 día)
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 1 semana

    #PARA PRODUCCION ESTA CONFIGURACION
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)

    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)
    # Tiempo de vida del token de refresco cuando se usa para renovar (default: None)
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Permite renovar el refresh token cada vez que se usa
    'ROTATE_REFRESH_TOKENS': True,
    
    # Invalida los refresh tokens después de usarlos
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Actualiza la última hora de inicio de sesión del usuario
    'UPDATE_LAST_LOGIN': True,
}


#Configuracion de Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Testimonial API',
    'DESCRIPTION': 'API REST utilizada como Backend para la plataforma Testimonial',
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Testimonial',
        'email': 'support@testimonial-cms.com',
        'url': 'https://testimonial-cms.vercel.app/prueba',
    },
    #Orden de los tags en Swagger
    'TAGS': [
        {'name': 'Login', 'description': 'Operaciones de autenticación'},
        {'name': 'Token', 'description': 'Operaciones relacionadas con los tokens JWT'},
        {'name': 'Visitantes', 'description': 'Operaciones relacionadas con los Usuarios visitantes'},
        {'name': 'Editores', 'description': 'Operaciones relacionadas con las Usuarios Editores'},
        {'name': 'Administradores', 'description': 'Operaciones relacionadas con las Usuarios admins'},
        {'name': 'Categorias', 'description': 'Operaciones relacionadas con las Categorias'},
        {'name': 'Organizaciones', 'description': 'Operaciones relacionadas con las Organizaciones(Dominios)'},
        {'name': 'Testimonios', 'description': 'Operaciones relacionadas con los Testimonios'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    }
}

PWA_APP_NAME = 'Testimonial'
PWA_APP_DESCRIPTION = "Testimonial"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = "#1c4216"
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/images/icons/icon-72x72.png', 'sizes': '72x72'},
    {'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'},
    {'src': '/static/images/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/images/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/images/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/images/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/images/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/images/icons/icon-512x512.png', 'sizes': '512x512'},
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es'