# Generated by Django 5.2.8 on 2025-11-30 02:31

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='app_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
            ],
            options={
                'verbose_name': 'Editor',
                'verbose_name_plural': 'Editores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion_nombre', models.CharField(max_length=50, unique=True)),
                ('dominio', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('editores', models.ManyToManyField(blank=True, related_name='organizaciones_editables', to=settings.AUTH_USER_MODEL)),
                ('visitantes', models.ManyToManyField(blank=True, related_name='organizaciones_visitantes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_anonimo_username', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario_anonimo_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('api_key', models.CharField(max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=100, null=True)),
                ('enlace', models.CharField(blank=True, max_length=100, null=True)),
                ('archivos', models.JSONField(blank=True, default=list, null=True)),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('ranking', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('estado', models.CharField(choices=[('E', 'ESPERA'), ('A', 'APROBADO'), ('R', 'RECHAZADO'), ('P', 'PUBLICADO'), ('B', 'BORRADOR'), ('O', 'OCULTO')], default='E', max_length=1, verbose_name='Estado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_testimonios', to='app.categoria')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizacion', to='app.organizacion')),
                ('usuario_registrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_visitante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-fecha_comentario'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('usuario_registrado__isnull', True)), fields=('organizacion', 'usuario_anonimo_username', 'usuario_anonimo_email'), name='unique_anonimo_por_organizacion')],
                'unique_together': {('organizacion', 'usuario_registrado')},
            },
        ),
    ]
