# Generated by Django 5.2 on 2025-11-21 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='editores',
            field=models.ManyToManyField(blank=True, related_name='organizaciones_editables', to=settings.AUTH_USER_MODEL),
        ),
    ]
