# Generated by Django 5.2 on 2025-12-05 03:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, help_text='Foto de perfil del usuario', max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
